# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'studentdashboardUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resfile

class Ui_StudentDashboard(object):
    def setupUi(self, StudentDashboard):
        StudentDashboard.setObjectName("StudentDashboard")
        StudentDashboard.resize(950, 620)
        StudentDashboard.setStyleSheet("\n"
"    QWidget { background-color: #e8f5e9; }\n"
"\n"
"    QLabel#uniLogo, QLabel#engLogo {\n"
"        max-width: 110px;\n"
"        max-height: 110px;\n"
"        min-width: 110px;\n"
"        min-height: 110px;\n"
"        border-radius: 8px;\n"
"    }\n"
"\n"
"    QLabel#regLabel, QLabel#availLabel, QLabel#creditsLabel1, QLabel#creditsLabel2 {\n"
"        font-size: 20px;\n"
"        font-weight: bold;\n"
"        color: #0e4d32;\n"
"    }\n"
"\n"
"    QFrame#infoBox {\n"
"        background: #d0ece1;\n"
"        border: 2px solid #0e6b33;\n"
"        border-radius: 12px;\n"
"    }\n"
"\n"
"    QPushButton#registerButton, QPushButton#deleteButton {\n"
"        background-color: #0e6b33;\n"
"        color: white;\n"
"        font-size: 18px;\n"
"        padding: 10px 20px;\n"
"        border-radius: 10px;\n"
"    }\n"
"\n"
"    QPushButton#registerButton:hover, QPushButton#deleteButton:hover {\n"
"        background-color: #094d26;\n"
"    }\n"
"   ")
        self.mainLayout = QtWidgets.QVBoxLayout(StudentDashboard)
        self.mainLayout.setObjectName("mainLayout")
        self.logosLayout = QtWidgets.QHBoxLayout()
        self.logosLayout.setObjectName("logosLayout")
        self.uniLogo = QtWidgets.QLabel(StudentDashboard)
        self.uniLogo.setStyleSheet("image: url(:/images/Downloads/King_Abdulaziz_University_logo no back.png);")
        self.uniLogo.setPixmap(QtGui.QPixmap("King_Abdulaziz_University_logo_no_back.png"))
        self.uniLogo.setScaledContents(True)
        self.uniLogo.setObjectName("uniLogo")
        self.logosLayout.addWidget(self.uniLogo)
        self.engLogo = QtWidgets.QLabel(StudentDashboard)
        self.engLogo.setPixmap(QtGui.QPixmap("KAU_ENGNEERING_DEP-removebg-preview.png"))
        self.engLogo.setScaledContents(True)
        self.engLogo.setObjectName("engLogo")
        self.logosLayout.addWidget(self.engLogo)
        self.mainLayout.addLayout(self.logosLayout)
        self.infoBox = QtWidgets.QFrame(StudentDashboard)
        self.infoBox.setObjectName("infoBox")
        self.infoLayout = QtWidgets.QVBoxLayout(self.infoBox)
        self.infoLayout.setObjectName("infoLayout")
        self.studentName = QtWidgets.QLabel(self.infoBox)
        self.studentName.setObjectName("studentName")
        self.infoLayout.addWidget(self.studentName)
        self.studentID = QtWidgets.QLabel(self.infoBox)
        self.studentID.setObjectName("studentID")
        self.infoLayout.addWidget(self.studentID)
        self.studentMajor = QtWidgets.QLabel(self.infoBox)
        self.studentMajor.setObjectName("studentMajor")
        self.infoLayout.addWidget(self.studentMajor)
        self.mainLayout.addWidget(self.infoBox)
        self.creditsLayout = QtWidgets.QHBoxLayout()
        self.creditsLayout.setObjectName("creditsLayout")
        self.creditsLabel1 = QtWidgets.QLabel(StudentDashboard)
        self.creditsLabel1.setObjectName("creditsLabel1")
        self.creditsLayout.addWidget(self.creditsLabel1)
        self.creditsLabel2 = QtWidgets.QLabel(StudentDashboard)
        self.creditsLabel2.setObjectName("creditsLabel2")
        self.creditsLayout.addWidget(self.creditsLabel2)
        self.mainLayout.addLayout(self.creditsLayout)
        self.coursesLayout = QtWidgets.QHBoxLayout()
        self.coursesLayout.setObjectName("coursesLayout")
        self.registeredLayout = QtWidgets.QVBoxLayout()
        self.registeredLayout.setObjectName("registeredLayout")
        self.regLabel = QtWidgets.QLabel(StudentDashboard)
        self.regLabel.setObjectName("regLabel")
        self.registeredLayout.addWidget(self.regLabel)
        self.registeredList = QtWidgets.QListWidget(StudentDashboard)
        self.registeredList.setObjectName("registeredList")
        self.registeredLayout.addWidget(self.registeredList)
        self.deleteButton = QtWidgets.QPushButton(StudentDashboard)
        self.deleteButton.setObjectName("deleteButton")
        self.registeredLayout.addWidget(self.deleteButton)
        self.coursesLayout.addLayout(self.registeredLayout)
        self.availableLayout = QtWidgets.QVBoxLayout()
        self.availableLayout.setObjectName("availableLayout")
        self.availLabel = QtWidgets.QLabel(StudentDashboard)
        self.availLabel.setObjectName("availLabel")
        self.availableLayout.addWidget(self.availLabel)
        self.availableList = QtWidgets.QListWidget(StudentDashboard)
        self.availableList.setObjectName("availableList")
        self.availableLayout.addWidget(self.availableList)
        self.registerButton = QtWidgets.QPushButton(StudentDashboard)
        self.registerButton.setObjectName("registerButton")
        self.availableLayout.addWidget(self.registerButton)
        self.coursesLayout.addLayout(self.availableLayout)
        self.mainLayout.addLayout(self.coursesLayout)

        self.retranslateUi(StudentDashboard)
        QtCore.QMetaObject.connectSlotsByName(StudentDashboard)

    def retranslateUi(self, StudentDashboard):
        _translate = QtCore.QCoreApplication.translate
        StudentDashboard.setWindowTitle(_translate("StudentDashboard", "KAU Engineering - Student Dashboard"))
        self.studentName.setText(_translate("StudentDashboard", "Student Name:"))
        self.studentID.setText(_translate("StudentDashboard", "Student ID:"))
        self.studentMajor.setText(_translate("StudentDashboard", "Major:"))
        self.creditsLabel1.setText(_translate("StudentDashboard", "Registered Hours: 0"))
        self.creditsLabel2.setText(_translate("StudentDashboard", "Available Hours: 0"))
        self.regLabel.setText(_translate("StudentDashboard", "Registered Courses"))
        self.deleteButton.setText(_translate("StudentDashboard", "Delete Course"))
        self.availLabel.setText(_translate("StudentDashboard", "Available Courses"))
        self.registerButton.setText(_translate("StudentDashboard", "Register Course"))

